FROM nvcr.io/nvidia/rapidsai/base:25.02-cuda12.0-py3.12

# Install Python and other dependencies
# RUN apt-get update && apt-get install -y \
#     python3 \
#     python3-pip \
#     && rm -rf /var/lib/apt/lists/*

USER root

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# Optional: Create a symlink for python (if needed)
RUN ln -s /usr/bin/python3 /usr/bin/python

# This Dockerfile can include any additional setup you need.
RUN conda install -n base ipykernel --update-deps --force-reinstall
RUN apt-get install gcc
RUN export CC=gcc
RUN export CXX=g++

